apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-go
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: cloud-native-go
          image: rubiagatra/cloud-native-go:1.0.0
          ports:
            - containerPort: 8080
              protocol: TCP
