version: '3'
services: 
    microservice:
        build: .
        ports:
          - "8080:8080"
    nginx:
        image: "nginx:1.15.6"
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
        ports:
            - "80:80"
            - "443:443"
        links:
          - microservice
        depends_on:
          - microservice
